
class Response:
    text: str
    def close() -> None: ...
    def json() -> None: ...
def delete() -> None: ...
def get(url: str, headers:dict[str, str]) -> Response: ...
def head() -> None: ...
def patch() -> None: ...
def post(url: str, headers:dict[str, str], data:str) -> Response: ...
def put() -> None: ...
def request() -> None: ...
